### ISSUE TITLE
Create repo TODO list

### ISSUE THREAD

**Issue by mpostol** [it-p-lodz-pl/OOI.Gateway2Azure.Article#1]
## Preface 

All related work to prepare the repository for further development.
Follow [community recommended standards](https://opensource.guide/)

## Scope:

- [x] .gitignore
- [x] README.md
- [x] Repository description
- [x] License
- [x]  Code of conduct
- [x]  Contributing or use [default one](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file)
- [x] GitHub pages
- [x] Repository website
- [x] Info in the master project if applicable

**Comment by mpostol** [comment]
Contributes to mpostol/OPC-UA-OOI#423

**Comment by mpostol** [comment]
Done of forked.
